use std::collections::BTreeSet;
use std::error::Error;
use std::io::Write;
use std::path::PathBuf;

use clap::Parser;
use oorv_core::compile_refined_file;
use oorv_core::oorvir::refined::{
    AccessMode, ArithLogOp, Constant, ConstraintKind, ExprVariant, Expression, FloatTy, IntTy,
    StreamIdx, Type, UIntTy, OORVIR,
};

#[derive(Debug, Parser)]
#[command(
    name = "oorv2c",
    about = "Compile an OORV specification to C metadata with a limited executable subset"
)]
struct Args {
    /// Path to the OORV specification file.
    spec_path: PathBuf,

    /// Destination C file. When omitted, C is written to stdout.
    #[arg(short, long)]
    output: Option<PathBuf>,
}

fn main() -> Result<(), Box<dyn Error>> {
    let args = Args::parse();
    let ir = compile_refined_file(&args.spec_path).map_err(|e| e.boxed())?;
    let generated = generate_c_monitor(&ir, args.spec_path.display().to_string());

    match args.output {
        Some(path) => std::fs::write(path, generated)?,
        None => {
            let mut stdout = std::io::stdout().lock();
            stdout.write_all(generated.as_bytes())?;
        }
    }

    Ok(())
}

fn generate_c_monitor(ir: &OORVIR, source_label: String) -> String {
    let classified = classify_alarms(ir);
    let mut out = String::new();
    out.push_str("/* Generated by oorv2c from ");
    out.push_str(&escape_c_comment(&source_label));
    out.push_str(". */\n");
    out.push_str("#include <stdbool.h>\n");
    out.push_str("#include <stdint.h>\n");
    out.push_str("#include <stddef.h>\n");
    out.push_str("#include <stdio.h>\n\n");
    out.push_str("#define OORV_GENERATED_SOURCE \"");
    out.push_str(&escape_c_string(&source_label));
    out.push_str("\"\n\n");
    out.push_str("typedef struct OorvMonitor OorvMonitor;\n");
    out.push_str("struct OorvMonitor {\n");
    out.push_str("    uint64_t event_count;\n");
    out.push_str("};\n\n");
    out.push_str("void oorv_monitor_init(OorvMonitor *monitor) {\n");
    out.push_str("    monitor->event_count = 0;\n");
    out.push_str("}\n\n");
    out.push_str("void oorv_monitor_step(OorvMonitor *monitor) {\n");
    out.push_str("    monitor->event_count += 1;\n");
    out.push_str("}\n\n");

    out.push_str("static const char *const OORV_INPUT_STREAMS[] = {\n");
    for signal in &ir.signals {
        out.push_str("    \"");
        out.push_str(&escape_c_string(&signal.name));
        out.push_str("\",\n");
    }
    out.push_str("    NULL,\n");
    out.push_str("};\n\n");

    out.push_str("static const char *const OORV_CONSTRAINT_STREAMS[] = {\n");
    for constraint in &ir.constraints {
        out.push_str("    \"");
        out.push_str(&escape_c_string(&constraint.name));
        out.push_str("\",\n");
    }
    out.push_str("    NULL,\n");
    out.push_str("};\n\n");

    out.push_str("static const char *const OORV_ALARMS[] = {\n");
    for alarm in &ir.alarms {
        if let Some(constraint) = ir.constraints.get(alarm.constrain_idx.out_ix()) {
            out.push_str("    \"");
            out.push_str(&escape_c_string(&constraint.name));
            out.push_str("\",\n");
        }
    }
    out.push_str("    NULL,\n");
    out.push_str("};\n\n");

    out.push_str("enum {\n");
    out.push_str(&format!("    OORV_INPUT_COUNT = {},\n", ir.signals.len()));
    out.push_str(&format!(
        "    OORV_CONSTRAINT_COUNT = {},\n",
        ir.constraints.len()
    ));
    out.push_str(&format!("    OORV_ALARM_COUNT = {},\n", ir.alarms.len()));
    out.push_str(&format!(
        "    OORV_EXECUTABLE_ALARM_COUNT = {},\n",
        classified.executable.len()
    ));
    out.push_str(&format!(
        "    OORV_UNSUPPORTED_ALARM_COUNT = {},\n",
        classified.unsupported.len()
    ));
    out.push_str("    OORV_INPUT_STORAGE_COUNT = OORV_INPUT_COUNT == 0 ? 1 : OORV_INPUT_COUNT,\n");
    out.push_str("};\n\n");

    out.push_str("typedef enum OorvValueKind {\n");
    out.push_str("    OORV_VALUE_NONE = 0,\n");
    out.push_str("    OORV_VALUE_BOOL,\n");
    out.push_str("    OORV_VALUE_I64,\n");
    out.push_str("    OORV_VALUE_U64,\n");
    out.push_str("    OORV_VALUE_F64,\n");
    out.push_str("} OorvValueKind;\n\n");
    out.push_str("typedef struct OorvValue {\n");
    out.push_str("    OorvValueKind kind;\n");
    out.push_str("    union {\n");
    out.push_str("        bool b;\n");
    out.push_str("        int64_t i64;\n");
    out.push_str("        uint64_t u64;\n");
    out.push_str("        double f64;\n");
    out.push_str("    } as;\n");
    out.push_str("} OorvValue;\n\n");
    out.push_str("typedef struct OorvEvent {\n");
    out.push_str("    OorvValue values[OORV_INPUT_STORAGE_COUNT];\n");
    out.push_str("} OorvEvent;\n\n");

    out.push_str("size_t oorv_monitor_input_count(void) {\n");
    out.push_str("    return (size_t)OORV_INPUT_COUNT;\n");
    out.push_str("}\n\n");
    out.push_str("size_t oorv_monitor_constraint_count(void) {\n");
    out.push_str("    return (size_t)OORV_CONSTRAINT_COUNT;\n");
    out.push_str("}\n\n");
    out.push_str("size_t oorv_monitor_alarm_count(void) {\n");
    out.push_str("    return (size_t)OORV_ALARM_COUNT;\n");
    out.push_str("}\n\n");
    out.push_str("size_t oorv_monitor_executable_alarm_count(void) {\n");
    out.push_str("    return (size_t)OORV_EXECUTABLE_ALARM_COUNT;\n");
    out.push_str("}\n\n");
    out.push_str("size_t oorv_monitor_unsupported_alarm_count(void) {\n");
    out.push_str("    return (size_t)OORV_UNSUPPORTED_ALARM_COUNT;\n");
    out.push_str("}\n\n");
    out.push_str("const char *oorv_monitor_input_name(size_t index) {\n");
    out.push_str(
        "    return index < oorv_monitor_input_count() ? OORV_INPUT_STREAMS[index] : NULL;\n",
    );
    out.push_str("}\n\n");
    out.push_str("const char *oorv_monitor_constraint_name(size_t index) {\n");
    out.push_str("    return index < oorv_monitor_constraint_count() ? OORV_CONSTRAINT_STREAMS[index] : NULL;\n");
    out.push_str("}\n\n");
    out.push_str("const char *oorv_monitor_alarm_name(size_t index) {\n");
    out.push_str("    return index < oorv_monitor_alarm_count() ? OORV_ALARMS[index] : NULL;\n");
    out.push_str("}\n\n");
    out.push_str("void oorv_monitor_describe(FILE *out) {\n");
    out.push_str("    fprintf(out, \"inputs=%zu constraints=%zu alarms=%zu\\n\",\n");
    out.push_str("            oorv_monitor_input_count(), oorv_monitor_constraint_count(), oorv_monitor_alarm_count());\n");
    out.push_str("}\n\n");

    emit_event_api(&mut out);
    emit_executable_alarm_functions(&mut out, &classified.executable);
    emit_event_step(&mut out, &classified.executable);

    out.push_str("/* Constraint kinds preserved from the core IR:\n");
    for constraint in &ir.constraints {
        let kind = match &constraint.kind {
            ConstraintKind::Output(_) => "output",
            ConstraintKind::Alarm(_) => "alarm",
        };
        out.push_str(" * ");
        out.push_str(kind);
        out.push_str(": ");
        out.push_str(&escape_c_comment(&constraint.name));
        out.push('\n');
    }
    out.push_str(" */\n");

    out.push_str("\n/* oorv2c executable subset report:\n");
    out.push_str(
        " * The C backend evaluates stateless event-driven alarms whose guards lower to\n",
    );
    out.push_str(
        " * strict current-event accesses, constants, arithmetic, comparisons, and boolean connectives.\n",
    );
    for alarm in &classified.executable {
        out.push_str(" * executable alarm ");
        out.push_str(&alarm.alarm_index.to_string());
        out.push_str(": ");
        out.push_str(&escape_c_comment(&alarm.constraint_name));
        out.push_str(" -> ");
        out.push_str(&escape_c_comment(&alarm.message));
        out.push('\n');
    }
    for alarm in &classified.unsupported {
        out.push_str(" * unsupported alarm ");
        out.push_str(&alarm.alarm_index.to_string());
        out.push_str(": ");
        out.push_str(&escape_c_comment(&alarm.constraint_name));
        out.push_str(" (");
        out.push_str(&escape_c_comment(&alarm.reason));
        out.push_str(")\n");
    }
    out.push_str(" */\n");

    out
}

#[derive(Debug)]
struct AlarmClassification {
    executable: Vec<ExecutableAlarm>,
    unsupported: Vec<UnsupportedAlarm>,
}

#[derive(Debug)]
struct ExecutableAlarm {
    alarm_index: usize,
    constraint_name: String,
    condition: String,
    required_inputs: Vec<RequiredInput>,
    message: String,
}

#[derive(Debug)]
struct UnsupportedAlarm {
    alarm_index: usize,
    constraint_name: String,
    reason: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
struct RequiredInput {
    index: usize,
    kind: CValueKind,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum CValueKind {
    Bool,
    I64,
    U64,
    F64,
}

impl CValueKind {
    fn enum_name(self) -> &'static str {
        match self {
            CValueKind::Bool => "OORV_VALUE_BOOL",
            CValueKind::I64 => "OORV_VALUE_I64",
            CValueKind::U64 => "OORV_VALUE_U64",
            CValueKind::F64 => "OORV_VALUE_F64",
        }
    }

    fn getter(self) -> &'static str {
        match self {
            CValueKind::Bool => "oorv_event_get_bool",
            CValueKind::I64 => "oorv_event_get_i64",
            CValueKind::U64 => "oorv_event_get_u64",
            CValueKind::F64 => "oorv_event_get_f64",
        }
    }

    fn is_numeric(self) -> bool {
        matches!(self, CValueKind::I64 | CValueKind::U64 | CValueKind::F64)
    }

    fn is_integer(self) -> bool {
        matches!(self, CValueKind::I64 | CValueKind::U64)
    }
}

#[derive(Debug)]
struct CExpr {
    code: String,
    kind: CValueKind,
    required_inputs: BTreeSet<RequiredInput>,
}

#[derive(Debug)]
struct CCompileContext<'a> {
    ir: &'a OORVIR,
    current_constraint: StreamIdx,
}

fn classify_alarms(ir: &OORVIR) -> AlarmClassification {
    let mut executable = Vec::new();
    let mut unsupported = Vec::new();

    for (alarm_index, alarm) in ir.alarms.iter().enumerate() {
        let constraint_idx = alarm.constrain_idx.out_ix();
        let constraint_name = ir
            .constraints
            .get(constraint_idx)
            .map(|constraint| constraint.name.clone())
            .unwrap_or_else(|| format!("<invalid constraint {constraint_idx}>"));

        match compile_executable_alarm(ir, alarm_index, constraint_idx) {
            Ok(alarm) => executable.push(alarm),
            Err(reason) => unsupported.push(UnsupportedAlarm {
                alarm_index,
                constraint_name,
                reason,
            }),
        }
    }

    AlarmClassification {
        executable,
        unsupported,
    }
}

fn compile_executable_alarm(
    ir: &OORVIR,
    alarm_index: usize,
    constraint_idx: usize,
) -> Result<ExecutableAlarm, String> {
    let constraint = ir
        .constraints
        .get(constraint_idx)
        .ok_or_else(|| "alarm refers to a missing constraint stream".to_string())?;

    if !matches!(&constraint.kind, ConstraintKind::Alarm(_)) {
        return Err("constraint is not an alarm stream".to_string());
    }
    if constraint.eval.decls.len() != 1 {
        return Err("alarm has multiple eval clauses".to_string());
    }
    if constraint.start.condition.is_some() {
        return Err("alarm has a start condition".to_string());
    }
    if constraint.end.condition.is_some() {
        return Err("alarm has an end condition".to_string());
    }

    let clause = &constraint.eval.decls[0];
    let message = match &clause.expression.kind {
        ExprVariant::LoadConstant(Constant::Str(message)) => message.clone(),
        _ => return Err("alarm payload is not a constant string".to_string()),
    };

    let (condition, required_inputs) = match &clause.condition {
        Some(condition) => {
            let context = CCompileContext {
                ir,
                current_constraint: constraint.stream_idx,
            };
            let compiled = compile_c_expr(&context, condition)?;
            if compiled.kind != CValueKind::Bool {
                return Err("alarm guard does not compile to a boolean expression".to_string());
            }
            (
                compiled.code,
                compiled.required_inputs.into_iter().collect::<Vec<_>>(),
            )
        }
        None if constraint.params.is_empty() => ("true".to_string(), Vec::new()),
        None => {
            return Err("parameterized alarm has no event-local guard".to_string());
        }
    };

    Ok(ExecutableAlarm {
        alarm_index,
        constraint_name: constraint.name.clone(),
        condition,
        required_inputs,
        message,
    })
}

fn compile_c_expr(context: &CCompileContext<'_>, expr: &Expression) -> Result<CExpr, String> {
    if let Some(guard) = compile_self_identity_guard(context, expr)? {
        return Ok(guard);
    }

    match &expr.kind {
        ExprVariant::LoadConstant(constant) => compile_c_constant(&expr.annotation, constant),
        ExprVariant::StreamAccess {
            target,
            parameters,
            access_kind,
        } => compile_c_stream_access(context, *target, parameters, *access_kind),
        ExprVariant::ArithLog(op, args) => compile_c_arith_log(context, *op, args),
        ExprVariant::Ite {
            condition,
            consequence,
            alternative,
        } => compile_c_ite(context, condition, consequence, alternative),
        ExprVariant::ParameterAccess(_, _) => Err(
            "parameter access is only supported inside generated self-identity guards".to_string(),
        ),
        ExprVariant::FunctionParameterAccess(_) => {
            Err("function parameter access is not supported by the C subset".to_string())
        }
        ExprVariant::Tuple(_) | ExprVariant::TupleAccess(_, _) => {
            Err("tuple expressions are not supported by the C subset".to_string())
        }
        ExprVariant::Function(_, _) => {
            Err("function calls are not supported by the C subset".to_string())
        }
        ExprVariant::Convert { .. } => {
            Err("explicit conversions are not supported by the C subset".to_string())
        }
        ExprVariant::Default { .. } => Err(
            "historical/defaulted accesses are not supported by the stateless C subset".to_string(),
        ),
        ExprVariant::Quantified { .. } | ExprVariant::QuantifiedVar(_) => {
            Err("quantified expressions require runtime object-domain state".to_string())
        }
    }
}

fn compile_self_identity_guard(
    context: &CCompileContext<'_>,
    expr: &Expression,
) -> Result<Option<CExpr>, String> {
    let ExprVariant::ArithLog(ArithLogOp::Eq, args) = &expr.kind else {
        return Ok(None);
    };
    if args.len() != 2 {
        return Ok(None);
    }

    let required_input = match_self_identity_guard(context, &args[0], &args[1])
        .or_else(|| match_self_identity_guard(context, &args[1], &args[0]));

    if let Some(required_input) = required_input {
        let mut required_inputs = BTreeSet::new();
        required_inputs.insert(required_input?);
        return Ok(Some(CExpr {
            code: "true".to_string(),
            kind: CValueKind::Bool,
            required_inputs,
        }));
    }

    Ok(None)
}

fn match_self_identity_guard(
    context: &CCompileContext<'_>,
    param_expr: &Expression,
    stream_expr: &Expression,
) -> Option<Result<RequiredInput, String>> {
    let ExprVariant::ParameterAccess(target, parameter_idx) = &param_expr.kind else {
        return None;
    };
    if *target != context.current_constraint || *parameter_idx != 0 {
        return None;
    }

    let ExprVariant::StreamAccess {
        target,
        parameters,
        access_kind,
    } = &stream_expr.kind
    else {
        return None;
    };
    if *access_kind != AccessMode::Strict || !parameters.is_empty() {
        return None;
    }

    let StreamIdx::Signal(signal_idx) = *target else {
        return Some(Err(
            "self-identity guard does not compare against an input signal".to_string(),
        ));
    };
    match expected_self_signal(context) {
        Ok(Some(expected)) if expected == *target => {}
        Ok(Some(_)) => {
            return Some(Err(
                "self-identity guard does not match the constraint start expression".to_string(),
            ));
        }
        Ok(None) => {
            return Some(Err(
                "self-identity guard has no constraint start expression to match".to_string(),
            ));
        }
        Err(reason) => return Some(Err(reason)),
    }
    let kind = match c_value_kind_for_type(&context.ir.signals[signal_idx].annotation) {
        Ok(kind) => kind,
        Err(reason) => return Some(Err(reason)),
    };

    Some(Ok(RequiredInput {
        index: signal_idx,
        kind,
    }))
}

fn expected_self_signal(context: &CCompileContext<'_>) -> Result<Option<StreamIdx>, String> {
    let StreamIdx::Constraint(constraint_idx) = context.current_constraint else {
        return Ok(None);
    };
    let Some(constraint) = context.ir.constraints.get(constraint_idx) else {
        return Err("current constraint index is out of bounds".to_string());
    };
    let Some(start_expr) = constraint.start.expression.as_ref() else {
        return Ok(None);
    };
    let ExprVariant::StreamAccess {
        target,
        parameters,
        access_kind,
    } = &start_expr.kind
    else {
        return Ok(None);
    };

    if *access_kind == AccessMode::Strict && parameters.is_empty() {
        Ok(Some(*target))
    } else {
        Ok(None)
    }
}

fn compile_c_constant(annotation: &Type, constant: &Constant) -> Result<CExpr, String> {
    let kind = c_value_kind_for_type(annotation)?;
    let code = match (kind, constant) {
        (CValueKind::Bool, Constant::Bool(value)) => {
            if *value {
                "true".to_string()
            } else {
                "false".to_string()
            }
        }
        (CValueKind::I64, Constant::Int(value)) => format!("((int64_t){value})"),
        (CValueKind::I64, Constant::UInt(value)) => format!("((int64_t){value})"),
        (CValueKind::U64, Constant::UInt(value)) => format!("((uint64_t){value})"),
        (CValueKind::U64, Constant::Int(value)) if *value >= 0 => {
            format!("((uint64_t){value})")
        }
        (CValueKind::F64, Constant::Float(value)) => format_c_float(*value)?,
        (CValueKind::F64, Constant::Decimal(value)) => Ok::<_, String>(value.to_string())?,
        (CValueKind::F64, Constant::Int(value)) => format!("((double){value})"),
        (CValueKind::F64, Constant::UInt(value)) => format!("((double){value})"),
        (_, Constant::Str(_)) => return Err("string constants are not scalar C values".to_string()),
        _ => {
            return Err(format!(
                "constant {:?} is incompatible with C scalar kind {:?}",
                constant, kind
            ))
        }
    };

    Ok(CExpr {
        code,
        kind,
        required_inputs: BTreeSet::new(),
    })
}

fn compile_c_stream_access(
    context: &CCompileContext<'_>,
    target: StreamIdx,
    parameters: &[Expression],
    access_kind: AccessMode,
) -> Result<CExpr, String> {
    if access_kind != AccessMode::Strict {
        return Err("only strict current-event stream accesses are executable in C".to_string());
    }
    if !parameters.is_empty() {
        return Err("parameterized stream accesses require runtime instance state".to_string());
    }

    let StreamIdx::Signal(signal_idx) = target else {
        return Err("constraint stream accesses require runtime state".to_string());
    };
    let kind = c_value_kind_for_type(&context.ir.signals[signal_idx].annotation)?;
    let mut required_inputs = BTreeSet::new();
    required_inputs.insert(RequiredInput {
        index: signal_idx,
        kind,
    });

    Ok(CExpr {
        code: format!("{}(event, (size_t){signal_idx})", kind.getter()),
        kind,
        required_inputs,
    })
}

fn compile_c_arith_log(
    context: &CCompileContext<'_>,
    op: ArithLogOp,
    args: &[Expression],
) -> Result<CExpr, String> {
    if let Some(guard) = compile_self_identity_guard(
        context,
        &Expression {
            kind: ExprVariant::ArithLog(op, args.to_vec()),
            annotation: Type::Bool,
        },
    )? {
        return Ok(guard);
    }

    let compiled = args
        .iter()
        .map(|arg| compile_c_expr(context, arg))
        .collect::<Result<Vec<_>, _>>()?;
    let required_inputs = merge_required_inputs(&compiled);

    match op {
        ArithLogOp::Not => {
            let [arg] = unary(&compiled, "logical not")?;
            require_kind(arg.kind, CValueKind::Bool, "logical not")?;
            Ok(CExpr {
                code: format!("(!({}))", arg.code),
                kind: CValueKind::Bool,
                required_inputs,
            })
        }
        ArithLogOp::Neg => {
            let [arg] = unary(&compiled, "numeric negation")?;
            require_numeric(arg.kind, "numeric negation")?;
            Ok(CExpr {
                code: format!("(-({}))", arg.code),
                kind: arg.kind,
                required_inputs,
            })
        }
        ArithLogOp::Add => compile_variadic_numeric("+", "addition", compiled, required_inputs),
        ArithLogOp::Sub => compile_variadic_numeric("-", "subtraction", compiled, required_inputs),
        ArithLogOp::Mul => {
            compile_variadic_numeric("*", "multiplication", compiled, required_inputs)
        }
        ArithLogOp::Div => compile_variadic_numeric("/", "division", compiled, required_inputs),
        ArithLogOp::Rem => compile_variadic_integer("%", "remainder", compiled, required_inputs),
        ArithLogOp::And => compile_variadic_bool("&&", "logical and", compiled, required_inputs),
        ArithLogOp::Or => compile_variadic_bool("||", "logical or", compiled, required_inputs),
        ArithLogOp::BitXor => {
            compile_variadic_integer("^", "bitwise xor", compiled, required_inputs)
        }
        ArithLogOp::BitAnd => {
            compile_variadic_integer("&", "bitwise and", compiled, required_inputs)
        }
        ArithLogOp::BitOr => compile_variadic_integer("|", "bitwise or", compiled, required_inputs),
        ArithLogOp::BitNot => {
            let [arg] = unary(&compiled, "bitwise not")?;
            require_integer(arg.kind, "bitwise not")?;
            Ok(CExpr {
                code: format!("(~({}))", arg.code),
                kind: arg.kind,
                required_inputs,
            })
        }
        ArithLogOp::Shl => compile_binary_integer("<<", "shift left", compiled, required_inputs),
        ArithLogOp::Shr => compile_binary_integer(">>", "shift right", compiled, required_inputs),
        ArithLogOp::Eq => compile_binary_comparison("==", "equality", compiled, required_inputs),
        ArithLogOp::Ne => compile_binary_comparison("!=", "inequality", compiled, required_inputs),
        ArithLogOp::Lt => compile_binary_order("<", "less-than", compiled, required_inputs),
        ArithLogOp::Le => compile_binary_order("<=", "less-or-equal", compiled, required_inputs),
        ArithLogOp::Ge => compile_binary_order(">=", "greater-or-equal", compiled, required_inputs),
        ArithLogOp::Gt => compile_binary_order(">", "greater-than", compiled, required_inputs),
        ArithLogOp::Pow => Err("power is not supported by the C subset".to_string()),
    }
}

fn compile_c_ite(
    context: &CCompileContext<'_>,
    condition: &Expression,
    consequence: &Expression,
    alternative: &Expression,
) -> Result<CExpr, String> {
    let condition = compile_c_expr(context, condition)?;
    require_kind(condition.kind, CValueKind::Bool, "conditional guard")?;
    let consequence = compile_c_expr(context, consequence)?;
    let alternative = compile_c_expr(context, alternative)?;
    if consequence.kind != alternative.kind {
        return Err("conditional branches have different C scalar kinds".to_string());
    }
    let required_inputs = merge_required_inputs([&condition, &consequence, &alternative]);

    Ok(CExpr {
        code: format!(
            "(({}) ? ({}) : ({}))",
            condition.code, consequence.code, alternative.code
        ),
        kind: consequence.kind,
        required_inputs,
    })
}

fn unary<'a>(args: &'a [CExpr], name: &str) -> Result<[&'a CExpr; 1], String> {
    if args.len() != 1 {
        return Err(format!("{name} expects exactly one operand"));
    }
    Ok([&args[0]])
}

fn binary<'a>(args: &'a [CExpr], name: &str) -> Result<[&'a CExpr; 2], String> {
    if args.len() != 2 {
        return Err(format!("{name} expects exactly two operands"));
    }
    Ok([&args[0], &args[1]])
}

fn compile_variadic_numeric(
    operator: &str,
    name: &str,
    args: Vec<CExpr>,
    required_inputs: BTreeSet<RequiredInput>,
) -> Result<CExpr, String> {
    if args.is_empty() {
        return Err(format!("{name} expects at least one operand"));
    }
    let kind = args[0].kind;
    require_numeric(kind, name)?;
    for arg in &args[1..] {
        require_kind(arg.kind, kind, name)?;
    }
    Ok(CExpr {
        code: join_exprs(operator, &args),
        kind,
        required_inputs,
    })
}

fn compile_variadic_integer(
    operator: &str,
    name: &str,
    args: Vec<CExpr>,
    required_inputs: BTreeSet<RequiredInput>,
) -> Result<CExpr, String> {
    if args.is_empty() {
        return Err(format!("{name} expects at least one operand"));
    }
    let kind = args[0].kind;
    require_integer(kind, name)?;
    for arg in &args[1..] {
        require_kind(arg.kind, kind, name)?;
    }
    Ok(CExpr {
        code: join_exprs(operator, &args),
        kind,
        required_inputs,
    })
}

fn compile_variadic_bool(
    operator: &str,
    name: &str,
    args: Vec<CExpr>,
    required_inputs: BTreeSet<RequiredInput>,
) -> Result<CExpr, String> {
    if args.is_empty() {
        return Err(format!("{name} expects at least one operand"));
    }
    for arg in &args {
        require_kind(arg.kind, CValueKind::Bool, name)?;
    }
    Ok(CExpr {
        code: join_exprs(operator, &args),
        kind: CValueKind::Bool,
        required_inputs,
    })
}

fn compile_binary_integer(
    operator: &str,
    name: &str,
    args: Vec<CExpr>,
    required_inputs: BTreeSet<RequiredInput>,
) -> Result<CExpr, String> {
    let [left, right] = binary(&args, name)?;
    require_integer(left.kind, name)?;
    require_integer(right.kind, name)?;
    Ok(CExpr {
        code: format!("(({}) {} ({}))", left.code, operator, right.code),
        kind: left.kind,
        required_inputs,
    })
}

fn compile_binary_comparison(
    operator: &str,
    name: &str,
    args: Vec<CExpr>,
    required_inputs: BTreeSet<RequiredInput>,
) -> Result<CExpr, String> {
    let [left, right] = binary(&args, name)?;
    require_kind(right.kind, left.kind, name)?;
    Ok(CExpr {
        code: format!("(({}) {} ({}))", left.code, operator, right.code),
        kind: CValueKind::Bool,
        required_inputs,
    })
}

fn compile_binary_order(
    operator: &str,
    name: &str,
    args: Vec<CExpr>,
    required_inputs: BTreeSet<RequiredInput>,
) -> Result<CExpr, String> {
    let [left, right] = binary(&args, name)?;
    require_numeric(left.kind, name)?;
    require_kind(right.kind, left.kind, name)?;
    Ok(CExpr {
        code: format!("(({}) {} ({}))", left.code, operator, right.code),
        kind: CValueKind::Bool,
        required_inputs,
    })
}

fn join_exprs(operator: &str, args: &[CExpr]) -> String {
    if args.len() == 1 {
        return args[0].code.clone();
    }

    let mut out = String::from("(");
    for (idx, arg) in args.iter().enumerate() {
        if idx > 0 {
            out.push(' ');
            out.push_str(operator);
            out.push(' ');
        }
        out.push('(');
        out.push_str(&arg.code);
        out.push(')');
    }
    out.push(')');
    out
}

fn require_kind(actual: CValueKind, expected: CValueKind, name: &str) -> Result<(), String> {
    if actual == expected {
        Ok(())
    } else {
        Err(format!(
            "{name} expects {:?} operands but found {:?}",
            expected, actual
        ))
    }
}

fn require_numeric(kind: CValueKind, name: &str) -> Result<(), String> {
    if kind.is_numeric() {
        Ok(())
    } else {
        Err(format!("{name} expects numeric operands"))
    }
}

fn require_integer(kind: CValueKind, name: &str) -> Result<(), String> {
    if kind.is_integer() {
        Ok(())
    } else {
        Err(format!("{name} expects integer operands"))
    }
}

fn merge_required_inputs<'a>(
    exprs: impl IntoIterator<Item = &'a CExpr>,
) -> BTreeSet<RequiredInput> {
    exprs
        .into_iter()
        .flat_map(|expr| expr.required_inputs.iter().copied())
        .collect()
}

fn c_value_kind_for_type(ty: &Type) -> Result<CValueKind, String> {
    match ty {
        Type::Bool => Ok(CValueKind::Bool),
        Type::Int(IntTy::Int8 | IntTy::Int16 | IntTy::Int32 | IntTy::Int64) => Ok(CValueKind::I64),
        Type::UInt(UIntTy::UInt8 | UIntTy::UInt16 | UIntTy::UInt32 | UIntTy::UInt64) => {
            Ok(CValueKind::U64)
        }
        Type::Float(FloatTy::Float32 | FloatTy::Float64) => Ok(CValueKind::F64),
        Type::Int(IntTy::Int128 | IntTy::Int256) => {
            Err("128-bit and 256-bit signed integers are not supported by the C subset".to_string())
        }
        Type::UInt(UIntTy::UInt128 | UIntTy::UInt256) => Err(
            "128-bit and 256-bit unsigned integers are not supported by the C subset".to_string(),
        ),
        Type::Fixed(_) | Type::UFixed(_) => {
            Err("fixed-point values are not supported by the C subset".to_string())
        }
        Type::String | Type::Bytes | Type::Tuple(_) | Type::Option(_) | Type::Function { .. } => {
            Err(format!("type {:?} is not a scalar C event value", ty))
        }
    }
}

fn format_c_float(value: f64) -> Result<String, String> {
    if !value.is_finite() {
        return Err("non-finite floating-point constants are not supported".to_string());
    }
    let mut rendered = value.to_string();
    if !rendered.contains('.') && !rendered.contains('e') && !rendered.contains('E') {
        rendered.push_str(".0");
    }
    Ok(rendered)
}

fn emit_event_api(out: &mut String) {
    out.push_str("void oorv_event_clear(OorvEvent *event) {\n");
    out.push_str("    if (event == NULL) {\n");
    out.push_str("        return;\n");
    out.push_str("    }\n");
    out.push_str("    for (size_t i = 0; i < (size_t)OORV_INPUT_COUNT; ++i) {\n");
    out.push_str("        event->values[i].kind = OORV_VALUE_NONE;\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("void oorv_event_set_bool(OorvEvent *event, size_t index, bool value) {\n");
    out.push_str("    if (event == NULL || index >= (size_t)OORV_INPUT_COUNT) {\n");
    out.push_str("        return;\n");
    out.push_str("    }\n");
    out.push_str("    event->values[index].kind = OORV_VALUE_BOOL;\n");
    out.push_str("    event->values[index].as.b = value;\n");
    out.push_str("}\n\n");

    out.push_str("void oorv_event_set_i64(OorvEvent *event, size_t index, int64_t value) {\n");
    out.push_str("    if (event == NULL || index >= (size_t)OORV_INPUT_COUNT) {\n");
    out.push_str("        return;\n");
    out.push_str("    }\n");
    out.push_str("    event->values[index].kind = OORV_VALUE_I64;\n");
    out.push_str("    event->values[index].as.i64 = value;\n");
    out.push_str("}\n\n");

    out.push_str("void oorv_event_set_u64(OorvEvent *event, size_t index, uint64_t value) {\n");
    out.push_str("    if (event == NULL || index >= (size_t)OORV_INPUT_COUNT) {\n");
    out.push_str("        return;\n");
    out.push_str("    }\n");
    out.push_str("    event->values[index].kind = OORV_VALUE_U64;\n");
    out.push_str("    event->values[index].as.u64 = value;\n");
    out.push_str("}\n\n");

    out.push_str("void oorv_event_set_f64(OorvEvent *event, size_t index, double value) {\n");
    out.push_str("    if (event == NULL || index >= (size_t)OORV_INPUT_COUNT) {\n");
    out.push_str("        return;\n");
    out.push_str("    }\n");
    out.push_str("    event->values[index].kind = OORV_VALUE_F64;\n");
    out.push_str("    event->values[index].as.f64 = value;\n");
    out.push_str("}\n\n");

    out.push_str(
        "bool oorv_event_has_kind(const OorvEvent *event, size_t index, OorvValueKind kind) {\n",
    );
    out.push_str("    return event != NULL && index < (size_t)OORV_INPUT_COUNT && event->values[index].kind == kind;\n");
    out.push_str("}\n\n");

    out.push_str("bool oorv_event_get_bool(const OorvEvent *event, size_t index) {\n");
    out.push_str("    if (!oorv_event_has_kind(event, index, OORV_VALUE_BOOL)) {\n");
    out.push_str("        return false;\n");
    out.push_str("    }\n");
    out.push_str("    return event->values[index].as.b;\n");
    out.push_str("}\n\n");
    out.push_str("int64_t oorv_event_get_i64(const OorvEvent *event, size_t index) {\n");
    out.push_str("    if (!oorv_event_has_kind(event, index, OORV_VALUE_I64)) {\n");
    out.push_str("        return 0;\n");
    out.push_str("    }\n");
    out.push_str("    return event->values[index].as.i64;\n");
    out.push_str("}\n\n");
    out.push_str("uint64_t oorv_event_get_u64(const OorvEvent *event, size_t index) {\n");
    out.push_str("    if (!oorv_event_has_kind(event, index, OORV_VALUE_U64)) {\n");
    out.push_str("        return 0;\n");
    out.push_str("    }\n");
    out.push_str("    return event->values[index].as.u64;\n");
    out.push_str("}\n\n");
    out.push_str("double oorv_event_get_f64(const OorvEvent *event, size_t index) {\n");
    out.push_str("    if (!oorv_event_has_kind(event, index, OORV_VALUE_F64)) {\n");
    out.push_str("        return 0.0;\n");
    out.push_str("    }\n");
    out.push_str("    return event->values[index].as.f64;\n");
    out.push_str("}\n\n");
}

fn emit_executable_alarm_functions(out: &mut String, alarms: &[ExecutableAlarm]) {
    for alarm in alarms {
        out.push_str("bool oorv_monitor_alarm_");
        out.push_str(&alarm.alarm_index.to_string());
        out.push_str("_inputs_ready(const OorvEvent *event) {\n");
        if alarm.required_inputs.is_empty() {
            out.push_str("    (void)event;\n");
            out.push_str("    return true;\n");
        } else {
            out.push_str("    return event != NULL");
            for required in &alarm.required_inputs {
                out.push_str("\n        && oorv_event_has_kind(event, (size_t)");
                out.push_str(&required.index.to_string());
                out.push_str(", ");
                out.push_str(required.kind.enum_name());
                out.push(')');
            }
            out.push_str(";\n");
        }
        out.push_str("}\n\n");

        out.push_str("bool oorv_monitor_eval_alarm_");
        out.push_str(&alarm.alarm_index.to_string());
        out.push_str("(const OorvEvent *event) {\n");
        out.push_str("    (void)event;\n");
        out.push_str("    return ");
        out.push_str(&alarm.condition);
        out.push_str(";\n");
        out.push_str("}\n\n");
    }
}

fn emit_event_step(out: &mut String, alarms: &[ExecutableAlarm]) {
    out.push_str("size_t oorv_monitor_step_event(OorvMonitor *monitor, const OorvEvent *event, size_t *alarms, size_t alarm_capacity) {\n");
    out.push_str("    (void)alarms;\n");
    out.push_str("    (void)alarm_capacity;\n");
    out.push_str("    if (monitor == NULL || event == NULL) {\n");
    out.push_str("        return 0;\n");
    out.push_str("    }\n");
    out.push_str("    monitor->event_count += 1;\n");
    out.push_str("    size_t written = 0;\n");
    for alarm in alarms {
        let idx = alarm.alarm_index.to_string();
        out.push_str("    if (oorv_monitor_alarm_");
        out.push_str(&idx);
        out.push_str("_inputs_ready(event) && oorv_monitor_eval_alarm_");
        out.push_str(&idx);
        out.push_str("(event)) {\n");
        out.push_str("        if (alarms != NULL && written < alarm_capacity) {\n");
        out.push_str("            alarms[written] = (size_t)");
        out.push_str(&idx);
        out.push_str(";\n");
        out.push_str("        }\n");
        out.push_str("        written += 1;\n");
        out.push_str("    }\n");
    }
    out.push_str("    return written;\n");
    out.push_str("}\n\n");
}

fn escape_c_string(input: &str) -> String {
    input
        .chars()
        .flat_map(|ch| match ch {
            '\\' => "\\\\".chars().collect::<Vec<_>>(),
            '"' => "\\\"".chars().collect::<Vec<_>>(),
            '\n' => "\\n".chars().collect::<Vec<_>>(),
            '\r' => "\\r".chars().collect::<Vec<_>>(),
            '\t' => "\\t".chars().collect::<Vec<_>>(),
            other => vec![other],
        })
        .collect()
}

fn escape_c_comment(input: &str) -> String {
    input.replace("*/", "* /")
}
